### ISSUE TITLE
Update to latest Cake

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Coveralls#12]
- This will include a pre-release version in order to get things to build correctly

**Comment by gep13** [comment]
Actually, can't do this just now, due to issue with dependency on Cake.Testing.

@patriksvensson am I right in saying that this has been corrected?

**Comment by patriksvensson** [comment]
@gep13 Yes, this should be fixed in 0.18.0.

**Comment by gep13** [comment]
@patriksvensson cool, will hold off on this issue until the release then.

**Comment by gep13** [comment]
Updated to 0.17.0 thanks to @devlead
