### ISSUE TITLE
Support coveralls.net on linux and os x

### ISSUE THREAD

**Issue by AdmiringWorm** [cake-contrib/Cake.Coveralls#38]
The current version of Cake.Coveralls only resolves the path to the Coveralls.Net executable on windows.

Since Coveralls.Net is now a .NET Core utility, on Unix platforms they do not contain the `.exe` part of the filename.

The filename on Unix platforms are now: `csmacnz.Coveralls` (Remember case-sensitivity).
It would be awesome if the addin could support resolving with that name as well.

**Comment by AdmiringWorm** [comment]
Seems like this is covered in the open pull request #33 (didn't take a look until after opening this issue).

**Comment by derhally** [comment]
@gep13 any chance we can have that PR reviewed?

**Comment by AdmiringWorm** [comment]
yay
